language: python
ignore_all_files_in_gitignore: true
ignored_paths: []
read_only: false

excluded_tools: []

initial_prompt: |
  Project Synapse ¨C Insight Generator agent.
  - Orchestrator starts in src/lib/ai.ts (findSynapticLink)
  - Agent loop in src/agentic/agenticLoop.ts
  - Planner in src/agentic/planner.ts
  - Types in src/agentic/types.ts
  - Adapters in src/agentic/adapters/

project_name: "synapse"